### ISSUE TITLE
I'm getting this while composer update/install

### ISSUE THREAD

**Issue by notbotman** [AlfredoRamos/parsedown-extra-laravel#24]
```
Class ParsedownExtraTest located in C:/Users/Yo/Desktop/secretproject/vendor/erusev/parsedown-extra\test\ParsedownExtraTest.php does not comply with psr-0 autoloading standard. Skipping.
```

Any Ideas, how to fix it?

**Comment by AlfredoRamos** [comment]
> Any Ideas, how to fix it?

Without the full context, because I don't even know where that message is coming from, I could only suggest you to:

1. Remove that file, since it's only useful for unit testing
2. Ignore the message, if it's not critical (does not stop the execution)

Anyways, that's not directly related to this package, so you should open a issue upstreams ([erusev/parsedown-extra](https://github.com/erusev/parsedown-extra)) if you believe it's a bug, however due to the lack of information, I guess it's not.

**Comment by AlfredoRamos** [comment]
I just tested it locally.

You can ignore the message, unfortunately it's not something I can nor should fix on my end.

https://github.com/erusev/parsedown/issues/763
https://github.com/erusev/parsedown-extra/issues/150
